---
baseURL: 'https://lovecraft-audio.pl'
languageCode: pl-pl
theme: color-your-world
title: 'lovecraft-audio.pl - indeks audiobooków z opowiadaniami H.P. Lovecrafta'
enableRobotsTXT: true

buildDrafts: false

params:
  owner: Daniel Skowroński
  style:
    isDark: true
    lightAccent: "lemon"
    darkAccent: "gold"


markup:
  goldmark:
    renderer:
      unsafe: true
